"""Versioned media-analysis models and bounded download primitives."""

from wxcli.media.downloader import (
    APPROVED_MEDIA_HOSTS,
    DownloadedMedia,
    HostResolver,
    MediaDownloader,
    MediaDownloadFailure,
    SystemHostResolver,
)

from wxcli.media.models import (
    MEDIA_EVIDENCE_EXTRACTOR_VERSION,
    MEDIA_EVIDENCE_SCHEMA_VERSION,
    MEDIA_RESULT_SCHEMA_VERSION,
    MediaAnalysisConfiguration,
    MediaAnalysisLimits,
    MediaAnalysisResult,
    MediaEvidence,
    MediaFormat,
    MediaItemEvidence,
    MediaItemReason,
    MediaItemStatus,
    MediaSummary,
    OCREvidence,
    OCRStatus,
    QREvidence,
    QRPayloadEvidence,
    QRPayloadType,
    QRStatus,
    build_media_evidence,
)

__all__ = [
    "APPROVED_MEDIA_HOSTS",
    "DownloadedMedia",
    "HostResolver",
    "MEDIA_EVIDENCE_EXTRACTOR_VERSION",
    "MEDIA_EVIDENCE_SCHEMA_VERSION",
    "MEDIA_RESULT_SCHEMA_VERSION",
    "MediaAnalysisConfiguration",
    "MediaAnalysisLimits",
    "MediaAnalysisResult",
    "MediaDownloader",
    "MediaDownloadFailure",
    "MediaEvidence",
    "MediaFormat",
    "MediaItemEvidence",
    "MediaItemReason",
    "MediaItemStatus",
    "MediaSummary",
    "OCREvidence",
    "OCRStatus",
    "QREvidence",
    "QRPayloadEvidence",
    "QRPayloadType",
    "QRStatus",
    "SystemHostResolver",
    "build_media_evidence",
]
