"""Versioned media-analysis models and bounded download primitives."""

from wxcli.media.cache import (
    MAX_MEDIA_CACHE_BYTES,
    MEDIA_CACHE_SCHEMA_VERSION,
    MEDIA_CACHE_TTL,
    CachedMedia,
    MediaCache,
    MediaCacheCleanup,
)
from wxcli.media.downloader import (
    APPROVED_MEDIA_HOSTS,
    DownloadedMedia,
    HostResolver,
    MediaDownloader,
    MediaDownloadFailure,
    SystemHostResolver,
)

from wxcli.media.models import (
    MEDIA_EVIDENCE_EXTRACTOR_VERSION,
    MEDIA_EVIDENCE_SCHEMA_VERSION,
    MEDIA_RESULT_SCHEMA_VERSION,
    MediaAnalysisConfiguration,
    MediaAnalysisLimits,
    MediaAnalysisResult,
    MediaEvidence,
    MediaFormat,
    MediaItemEvidence,
    MediaItemReason,
    MediaItemStatus,
    MediaSummary,
    OCREvidence,
    OCRStatus,
    QREvidence,
    QRPayloadEvidence,
    QRPayloadType,
    QRStatus,
    build_media_evidence,
)
from wxcli.media.orchestration import (
    ArticleMediaDownloader,
    ArticleMediaDownloads,
    BoundedMediaDownloader,
    MediaAcquisitionItem,
    MediaAcquisitionStatus,
)
from wxcli.media.qr import (
    STANDARD_QR_ANALYZER,
    STANDARD_QR_ANALYZER_VERSION,
    StandardQRAnalyzer,
    StandardQRDecoder,
    ZXingStandardQRDecoder,
)

__all__ = [
    "APPROVED_MEDIA_HOSTS",
    "ArticleMediaDownloader",
    "ArticleMediaDownloads",
    "BoundedMediaDownloader",
    "CachedMedia",
    "DownloadedMedia",
    "HostResolver",
    "MAX_MEDIA_CACHE_BYTES",
    "MEDIA_CACHE_SCHEMA_VERSION",
    "MEDIA_CACHE_TTL",
    "MEDIA_EVIDENCE_EXTRACTOR_VERSION",
    "MEDIA_EVIDENCE_SCHEMA_VERSION",
    "MEDIA_RESULT_SCHEMA_VERSION",
    "MediaAnalysisConfiguration",
    "MediaAnalysisLimits",
    "MediaAnalysisResult",
    "MediaAcquisitionItem",
    "MediaAcquisitionStatus",
    "MediaCache",
    "MediaCacheCleanup",
    "MediaDownloader",
    "MediaDownloadFailure",
    "MediaEvidence",
    "MediaFormat",
    "MediaItemEvidence",
    "MediaItemReason",
    "MediaItemStatus",
    "MediaSummary",
    "OCREvidence",
    "OCRStatus",
    "QREvidence",
    "QRPayloadEvidence",
    "QRPayloadType",
    "QRStatus",
    "STANDARD_QR_ANALYZER",
    "STANDARD_QR_ANALYZER_VERSION",
    "StandardQRAnalyzer",
    "StandardQRDecoder",
    "SystemHostResolver",
    "ZXingStandardQRDecoder",
    "build_media_evidence",
]
